project_id = "lddlzlthtwuwxxrrbxuc"

[functions.activities]
verify_jwt = false

[functions.mock-activities]
verify_jwt = false

[functions.bookings]
verify_jwt = false

[functions.bookings-parent-validate]
verify_jwt = false

[functions.simulate-aid]
verify_jwt = false

[functions.modal-split]
verify_jwt = false

[functions.reports]
verify_jwt = false

[functions.google-maps-token]
verify_jwt = false

[functions.google-maps-directions]
verify_jwt = false