[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    fail_deploy_on_score_thresholds = "false"

  [plugins.inputs.thresholds]
    performance    = 0.9
    accessibility  = 1.0
    best-practices = 0.9
    seo            = 0.8
    pwa            = 0.5
